name: Release
on:
    # allow for manual triggers
    workflow_dispatch: {}
    push:
        branches:
            - release

jobs:
    core:
        uses: paypal/paypal-messaging-components/.github/workflows/core.yml@release

    compareSnapshots:
        uses: paypal/paypal-messaging-components/.github/workflows/snapshotCompare.yml@release

    release:
        name: Release
        needs: [core, compareSnapshots]
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repo
              uses: actions/checkout@v3
              with:
                  persist-credentials: false
                  # pulls all commits (needed for semantic release to correctly version)
                  fetch-depth: '0'

            - name: Setup node
              uses: actions/setup-node@v3
              with:
                  node-version: 16
                  cache: 'npm'

            - name: Release
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              run: npx semantic-release@18
